name: 'Deploy'
on:
  push:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy: [true, false]'
        required: true
        default: 'false'

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # Needed for deployment to run correctly

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Install dependencies
      run: yarn install

    - name: Build production package
      run: yarn build

    - name: Deploy pages
      if: (github.event_name == 'push' || github.event.inputs.deploy == 'true')
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        SSH: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
        CLEAN_EXCLUDE: '[".gitattributes", ".gitignore", "CNAME", "LICENSE"]'
