name: 'Tests'
on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
  push:
    branches-ignore:
      - 'gh-pages'
  workflow_dispatch:
    branches-ignore:
      - 'gh-pages'
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Install dependencies
      run: yarn install

    - name: Run jest tests
      run: yarn test

      # Note: pull requests made via a forked repo do NOT have access to repository secrets
      # See https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
    - name: Run integration tests
      run: yarn integration
      env:
        API_KEY: ${{ secrets.TEST_API_KEY }}
        API_URL: ${{ secrets.TEST_API_URL }}

    - name: Run production build to ensure the build works
      run: yarn build
